### PR TITLE
allow organisation admin to view intern's profile

### PR DESCRIPTION
**Pull request by RamyAlshurafa**
Relates #40 
**need to be sure if all the intern's profile details should be visible to organization admin**

### CODE REVIEW

**Comment by MohammedYehia** [comment]
@RamyAlshurafa I think this doesn't work 
I logged as `an organisation` but I can't find my interns and can't see my interns profiles
is there a specific user should I test with?

**Comment by RamyAlshurafa** [comment]
@MohammedYehia 
1. yeah, interns can use coupons from multiple organizations
2. `should update the link on the organization dashboard` sorry, didn't get what you mean 
3. `if you clicked on the name of the intern on the discount table it will take you to /dashboard` it takes me to the intern's profile, make sure please you pulled the right branch
4.`is there another way to view a list of org interns without the discount table?` yeah from the updates section, but until now we don't create updates for organizations

**Comment by MohammedYehia** [comment]
@RamyAlshurafa 
I mean even if the intern doesn't belong to the organization the Org  would still see his profile, is this a normal thing or should the org only see its interns?

and for the /dashboard link see this pic 

profileOrg

I am on this branch with the last updates

**Comment by RamyAlshurafa** [comment]
@MohammedYehia 
thanks, will fix the link
I think we can keep this as any org can view any intern's profile
in this way the orgs can search for interns and see their profiles before creating them a coupon

**Comment by MohammedYehia** [comment]
@RamyAlshurafa 

> @MohammedYehia
> thanks, will fix the link
> I think we can keep this as any org can view any intern's profile
> in this way the orgs can search for interns and see their profiles before creating them a coupon

I agree with you 👍

**Comment by RamyAlshurafa** [comment]
@MohammedYehia 
re- the link could you double-check please, this is what I get
image

**Pull request closed without merging**
