### PR TITLE
small bugs

### PR DESCRIPTION
**Pull request by ahmedisam99**
relates #411

### CODE REVIEW

**Comment by thejoefriel** [comment]
Hey the code on this PR seems to be to do with a different issue than the related issue mentioned in the PR? For example, the bit on getting the profile pic. Does this PR relate to any other issues?

**Comment by ahmedisam99** [comment]
@thejoefriel 
We've decided here that any small bugs that we encounter shall be pushed on this branch and relate to that issue, and each commit should represent a bug on itself, check the commits.

The issue was originally created for the bug mentioned in it, but then we've decided that every small bug that we encounter should relate to it instead of opening a new issue for it.

Small bugs are limited to stuff like typos, invalid urls for the images, ...etc

**Comment by thejoefriel** [comment]
Ah ok thanks for that. Are you wanting this reviewed then or wait for you to do more bugs?

**Comment by ahmedisam99** [comment]
@thejoefriel 
better if got reviewed and merged acyually

**Pull request merged**
