### PR TITLE
Create review

### PR DESCRIPTION
**Pull request by FarahZaqout**
#113 

# adds the create review functionality (backend)
## New Files: (6)
 * added a controller for reviews (`controllers/review/index.js`)
 * added a query for creating reviews (2)
    * `/queries/review/index.js`
    * `/queries/review/createReview.js`
 * added a query for creating a type "getReview" notification. (2)
    * `/queries/notification/index.js`
    * `/queries/notification/createNotification.js`
 * added an integration test for the reviews endpoint (in __test__/api/)
## Modified Files: (5)
 * **constants:** added the reviews url endpoint
 * **apiRouter:** added the review route (with hard authentication)
 * **package.json (3):** ran audit fix on client and server packages, and added a test:current for my own use because running all the test suites on every new test case takes so much time.
## Flow of the Feature:
 1- User creates a review. Request goes to the ```REVIEW_URL```
 2- Authentication check passes. (only logged in users can add a review)
 3- Payload is verified. Rating and Message must be included. Otherwise a status **400** response.
 4- Review is created based on the payload.
 5 - Notification is created.
 6 - A success response is returned to the client.
## PR details:
* add review endpoint `/api/users/:id/reviews`.
* create a notification type: `getReview`.
* API endpoint `API endpoint: /api/users/:id/reviews` method `POST`
payload: 
```js
  {
    to, // id of the user who is being reviewed
    from, // reviewer id, should be received from params and checked with authentication.
    rating, // integer (number of stars)
    message // string
  }
```
## Test Cases:
 * **Success:** The user is authenticated and sends valid payload. Response: **200**.
    * a review is created with.
    * a notification is created with type: "getReview".
* **Input Validation Failure (2)**: the user creates a review without rating or without a message. Response 400.
    * each case has its own message to the user.
* **Unauthenticated User Review**: Response should be **401**. Test case not yet added.
* **Server Error**: Test case for response status **500**. Test case not yet added.

### CODE REVIEW

**Comment by FarahZaqout** [comment]
@RamyAlshurafa Hey man, I'm having some trouble with jest.
I got the request to send properly and the data is inserted successfully in the database, however I get some weird error and I don't know why.

Using Compass, the data is properly inserted both in the reviews and notifications collections.
## Review
image
## Notification
image

However, when I try to use ```findById``` like I'm trying in the test, it breaks with a weird error
```
CastError: Cast to ObjectId failed for value "{ secondParty: '5d3f67f2aa8f0703b68b9f53' }" at path "_id" for model "notifications"
```

**Comment by RamyAlshurafa** [comment]
Hey @FarahZaqout, I went through your code and get the error
you used `Notification.findById({ secondParty: reviewData.to })`
`findById` expect a single argument for Id, while you put an object
you have to use `findOne`  instead which accept an object

**Comment by FarahZaqout** [comment]
Yeah I feel so stupid man. I think the PR is ready for review now.

**Comment by FarahZaqout** [comment]
@RamyAlshurafa I agree but I wasn't sure of the pattern we are following. I do like the folder and index pattern and we probably should do it in queries, controllers and everywhere possible.
Also I need to document the flow of the PR.

**Pull request merged**
