### PR TITLE
reviews section

### LINKED ISSUE #358: Show host's and intern's reviews on their profiles
- [ ] Intern's profiles viewed by orgs and hosts
Intern Profile as seen by host   organisations
---
- [ ] host's profiles viewed by org and intern

Host listing before booking (2)

---
- [ ] booking page viewed by the host
Booking page for host showing next intern to stay (1)
---

- [ ] booking page viewed by intern
Booking page for intern (1)

### PR DESCRIPTION
**Pull request by RamyAlshurafa**
closes #358

### CODE REVIEW

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa Looks good. Just wondering though why it says the host hasn't hosted any interns but then shows a review? I'm assuming this is to do with the dummy data right? Should we simplify it and just have it say Reviews if there are reviews there to show? And if there are no reviews then "There are currently no reviews"

What do you think?

image

**Comment by RamyAlshurafa** [comment]
@ahmedisam99 check this

**Comment by ahmedisam99** [comment]
@thejoefriel 
hey there, it indeed does have to do with dummy data, as I attempted to add a review directly in the database without it being linked to an existing booking, that what created the conflict here and showed that Ramy hasn't stayed with any intern and got a review at the same time.

A review cannot be submitted without it being linked to a completed booking/stay

**Comment by thejoefriel** [comment]
OK thanks @ahmedisam99 - can we make just a small change then that it always says "Reviews" as the title rather than  that they haven't hosted anyone yet. If there are no reviews, then underneath we can just have "There are currently no reviews"

I feel this will be cleaner and more in line with similar platforms

**Pull request merged**
